# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jeongin Park
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Jeongin!
baseurl: "/bay" # the subpath of the site
url: "https://ZzeongB.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
    - name: Projects
    - name: Other experiences
    - name: Fun

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: parkjeong02@gmail.com
  follow:    
    - type: github
      name: GitHub
      link: http://github.com/ZzeongB
    
# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
